CREATE TABLE SJ_CM_CODE(CM_CODE TEXT PRIMARY KEY, CM_CODE_NM TEXT);

CREATE TABLE SJ_OBJ_CODE(OBJ_ID TEXT PRIMARY KEY, OBJ_CODE TEXT, OBJ_CODE_NM TEXT, REG_DATE TEXT, REG_USER TEXT);

CREATE TABLE SJ_EMP(EMP_ID TEXT PRIMARY KEY, EMP_NM TEXT);

CREATE TABLE SJ_USE_HIST(USE_HIST TEXT PRIMARY KEY, OBJ_ID TEXT, EMP_ID TEXT, RENT_DATE TEXT, RETURN_DATE TEXT,
FOREIGN KEY (OBJ_ID) REFERENCES SJ_OBJ_CODE(OBJ_ID), FOREIGN KEY (EMP_ID) REFERENCES SJ_EMP(EMP_ID));

CREATE TABLE SJ_FIX_HIST(FIX_HIST TEXT PRIMARY KEY, OBJ_ID TEXT, STTU TEXT, FIX_ORDER_DATE TEXT, FIX_FINISH_DATE TEXT, 
FOREIGN KEY (OBJ_ID) REFERENCES SJ_OBJ_CODE(OBJ_ID));

DROP TABLE SJ_CM_CODE; --table 삭제

pragma table_info(SJ_CM_CODE); --table 정보

pragma table_info(SJ_OBJ_CODE);

pragma table_info(SJ_EMP); --table 정보

pragma table_info(SJ_USE_HIST);

pragma table_info(SJ_FIX_HIST);

DROP TABLE SJ_FIX_HIST;

insert into SJ_CM_CODE values (123, 456);

select * from SJ_CM_CODE;